# Generated by Django 3.2.3 on 2021-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0002_specifications_participation_filtering'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='priority_spec',
            field=models.CharField(default=99, max_length=10),
        ),
    ]
