# Generated by Django 3.2.3 on 2021-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0003_specifications_priority_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproducts',
            name='name_cat',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
