# Generated by Django 3.2.3 on 2021-12-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0004_alter_categoryproducts_name_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproducts',
            name='name_cat',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
