# Generated by Django 3.2.3 on 2021-12-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0005_alter_categoryproducts_name_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifications.categoryproducts'),
        ),
    ]
