# Generated by Django 3.2.3 on 2021-12-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0007_valuesspec_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspec',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifications.categoryproducts'),
        ),
    ]
