# Generated by Django 3.2.3 on 2021-12-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0009_alter_productspec_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='category',
        ),
    ]
