# Generated by Django 3.2.3 on 2021-12-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0010_remove_productspec_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspec',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='specifications.categoryproducts'),
        ),
    ]
