# Generated by Django 3.1 on 2020-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200902_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageHome',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
