# Generated by Django 3.1 on 2020-09-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_imagehome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageHome',
        ),
    ]
