# Generated by Django 3.1 on 2020-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_imagehome'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageHome',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
