# Generated by Django 3.1 on 2020-09-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_imagehome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageHome',
            new_name='imageh',
        ),
    ]
