# Generated by Django 3.1 on 2020-09-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200903_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageh',
            new_name='image',
        ),
    ]
