# Generated by Django 3.1.1 on 2020-12-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0003_auto_20201004_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to='account.profile'),
            preserve_default=False,
        ),
    ]
