# Generated by Django 3.1.1 on 2020-12-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0004_orderitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='profile',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to='account.profile'),
            preserve_default=False,
        ),
    ]
