# Generated by Django 3.1.4 on 2020-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201205_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
